src/Fabien/EventsEngineBundle_old/Entity/Event.php
<?php

namespace Fabien\EventsEngineBundle\Entity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\HttpFoundation\File\UploadedFile;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * Event
 *
 * @ORM\Table(name="event")
 * @ORM\Entity(repositoryClass="Fabien\EventsEngineBundle\Repository\EventRepository")
 */
class Event
{

  /**
   * @ORM\ManyToOne(targetEntity="Fabien\EventsEngineBundle\Entity\TypeEvent", inversedBy="events")
   * @ORM\JoinColumn(nullable=false)
   */
  private $type_event;


  /**
   * @ORM\ManyToOne(targetEntity="Fabien\EventsEngineBundle\Entity\Country")
   * @ORM\JoinColumn(nullable=false)
   */
  private $country;



  /**
   * @ORM\ManyToOne(targetEntity="Fabien\EventsEngineBundle\Entity\City", inversedBy="events")
   * @ORM\JoinColumn(nullable=true)
   * @ORM\OrderBy({"title" = "ASC"})
   */
  private $city;

  /**
   * @ORM\OneToMany(targetEntity="Fabien\EventsEngineBundle\Entity\Date", mappedBy="event",cascade={"persist"}, orphanRemoval=true)
   */
  private $dates;

  /**
   * @ORM\ManyToOne(targetEntity="Fabien\EventsEngineBundle\Entity\Image", inversedBy="events")
   * @ORM\JoinColumn(name="image_id", referencedColumnName="id",nullable=true, onDelete="SET NULL")
   */
  private $image;

  /**
   * @Assert\Image(
   *     maxSize="1M",
   *  maxSizeMessage="Image trop volumineuse (max 1Mo)"
   * )
   */
  private $file;

  private $tempFilename;
  private $alt;


  public function __construct()
    {
      $this->dateInscription=null;
      $this->tocken=md5("ceciestuncodesecret".date("y:h:m:s"));
      $this->date_creation=new \Datetime();
      $this->date_update=new \Datetime();
      $this->dates = new ArrayCollection();
    }

    public function setImage(Image $image)
    {
      $this->image= $image;
      return $this;
    }


    public function getImage()
    {
      return $this->image;
    }




    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;


    /**
     * @var integer
     *
     * @ORM\Column(name="day", type="integer",nullable=true)
     */
    private $day;


    /**
     * @var string
     *
     * @ORM\Column(name="organizer", type="string", length=255, nullable=true)
     */
    private $organizer;


    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="url_web", type="string", length=255, nullable=true)
     */
    private $urlWeb;

    /**
     * @var string
     *
     * @ORM\Column(name="url_fb", type="string", length=255, nullable=true)
     */
    private $urlFb;

    /**
     * @var string
     *
     * @ORM\Column(name="adress", type="string", length=255)
     */
    private $adress;

    /**
     * @var string
     *
     * @ORM\Column(name="city_other", type="string", length=255, nullable=true)
     */
    private $city_other;

    /**
     * @var string
     *
     * @ORM\Column(name="origin", type="string", length=255, nullable=false)
     */
    private $origin;

    /**
     * @var string
     *
     * @ORM\Column(name="date_creation", type="datetime")
     */
    private $date_creation;

    /**
     * @var string
     *
     * @ORM\Column(name="date_update", type="datetime" , nullable=true)
     */
    private $date_update;

    /**
     * @var string
     *
     * @ORM\Column(name="mail_creator", length=255, nullable=true)
     */
    private $mail_creator;

    /**
     * @var string
     *
     * @ORM\Column(name="password_creator", length=255, nullable=true)
     */
    private $password_creator;



    /**
     * @var string
     *
     * @ORM\Column(name="tocken", length=255, nullable=false)
     */
    private $tocken;


    /**
     * @var bool
     *
     * @ORM\Column(name="gender_balance", type="boolean")
     */
    private $genderBalance;

    /**
     * @var bool
     *
     * @ORM\Column(name="publish", type="boolean",nullable=true)
     */
    private $publish;


    /**
     * @var int
     *
     * @ORM\Column(name="valorisation", type="integer",nullable=true)
     */
    private $valorisation;



    /**
     * @var bool
     *
     * @ORM\Column(name="inscription", type="boolean",nullable=true)
     */
    private $inscription;


    /**
     * @var string
     *
     * @ORM\Column(name="date_inscription", type="datetime",nullable=true)
     */
    private $dateInscription;


    /**
     * @var string
     *
     * @ORM\Column(name="lieu_raw", type="text", nullable=true)
     */
    private $lieuRaw;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Event
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }


    /**
     * Set lieuRaw
     *
     * @param string $lieuRaw
     *
     * @return Event
     */
    public function setLieuRaw($lieuRaw)
    {
        $this->lieuRaw = $lieuRaw;

        return $this;
    }

    /**
     * Get lieuRaw
     *
     * @return string
     */
    public function getLieuRaw()
    {
        return $this->lieuRaw;
    }


    /**
     * Set day
     *
     * @param string $day
     *
     * @return Event
     */
    public function setDay($day)
    {
        $this->day = $day;

        return $this;
    }

    /**
     * Get day
     *
     * @return integer
     */
    public function getDay()
    {
        return $this->day;
    }




    /**
     * Set description
     *
     * @param string $description
     *
     * @return Event
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set urlWeb
     *
     * @param string $urlWeb
     *
     * @return Event
     */
    public function setUrlWeb($urlWeb)
    {
        $this->urlWeb = $urlWeb;

        return $this;
    }

    /**
     * Get urlWeb
     *
     * @return string
     */
    public function getUrlWeb()
    {
        return $this->urlWeb;
    }

    /**
     * Set urlFb
     *
     * @param string $urlFb
     *
     * @return Event
     */
    public function setUrlFb($urlFb)
    {
        $this->urlFb = $urlFb;

        return $this;
    }

    /**
     * Get urlFb
     *
     * @return string
     */
    public function getUrlFb()
    {
        return $this->urlFb;
    }

    /**
     * Set adress
     *
     * @param string $adress
     *
     * @return Event
     */
    public function setAdress($adress)
    {
        $this->adress = $adress;

        return $this;
    }

    /**
     * Get adress
     *
     * @return string
     */
    public function getAdress()
    {
        return $this->adress;
    }


    /**
     * Set city_other
     *
     * @param string $city_other
     *
     * @return Event
     */
    public function setCityOther($city_other)
    {
        $this->city_other = $city_other;

        return $this;
    }

    /**
     * Get city_other
     *
     * @return string
     */
    public function getCityOther()
    {
        return $this->city_other;
    }




    /**
     * Set organizer
     *
     * @param string $organizer
     *
     * @return Event
     */
    public function setOrganizer($organizer)
    {
        $this->organizer = $organizer;

        return $this;
    }

    /**
     * Get organizer
     *
     * @return string
     */
    public function getOrganizer()
    {
        return $this->organizer;
    }



    /**
     * Set genderBalance
     *
     * @param boolean $genderBalance
     *
     * @return Event
     */
    public function setGenderBalance($genderBalance)
    {
        $this->genderBalance = $genderBalance;

        return $this;
    }

    /**
     * Get genderBalance
     *
     * @return bool
     */
    public function getGenderBalance()
    {
        return $this->genderBalance;
    }

    /**
     * Set publish
     *
     * @param boolean $publish
     *
     * @return Event
     */
    public function setPublish($publish)
    {
        $this->publish = $publish;

        return $this;
    }

    /**
     * Get publish
     *
     * @return bool
     */
    public function getPublish()
    {
        return $this->publish;
    }

    /**
     * Set typeEvent
     *
     * @param \Fabien\EventsEngineBundle\Entity\TypeEvent $typeEvent
     *
     * @return Event
     */
    public function setTypeEvent(\Fabien\EventsEngineBundle\Entity\TypeEvent $typeEvent)
    {
        $this->type_event = $typeEvent;

        return $this;
    }

    /**
     * Get typeEvent
     *
     * @return \Fabien\EventsEngineBundle\Entity\TypeEvent
     */
    public function getTypeEvent()
    {
        return $this->type_event;
    }



    /**
     * Set country
     *
     * @param \Fabien\EventsEngineBundle\Entity\Country $country
     *
     * @return Event
     */
    public function setCountry(\Fabien\EventsEngineBundle\Entity\Country $country)
    {
        $this->country = $country;

        return $this;
    }

    /**
     * Get Country
     *
     * @return \Fabien\EventsEngineBundle\Entity\Country
     */
    public function getCountry()
    {
        return $this->country;
    }





    /**
     * Set city
     *
     * @param \Fabien\EventsEngineBundle\Entity\City $city
     *
     * @return Event
     */

src/Fabien/EventsEngineBundle_old/Form/EventType.php
<?php

namespace Fabien\EventsEngineBundle\Form;

use Symfony\Component\Form\AbstractType;

use Symfony\Component\Security\Core\Authorization\AuthorizationChecker;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;

use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

use Fabien\EventsEngineBundle\repository\CityRepository;
use Fabien\EventsEngineBundle\repository\CountryRepository;
use Fabien\EventsEngineBundle\Entity\Country;
use Fabien\EventsEngineBundle\Entity\City;
use Fabien\EventsEngineBundle\Entity\Date;

class EventType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('title' ,     TextType::class, array('required'=>true,'label'=>"Titre de l'événement","attr"=>array("placeholder"=>"Exemple : Milonga du printemps ")))
        ->add('organizer',TextType::class,array('label'=>"Organisateur","attr"=>array("placeholder"=>"Exemple : Association Tangoloso"),'required' => false))
        ->add('description', TextareaType::class, array('required'=>1,'label'=>"Description", 'attr' => array('rows' => '20')))
        ->add('urlWeb', TextType::class, array('required'=>false,'label'=>"Site web","attr"=>array("placeholder"=>"Exemple : https://www.tangoloso.com")))
        ->add('urlFb',TextType::class, array('required'=>false,'label'=>"Adresse Facebook","attr"=>array("placeholder"=>"Exemple : https://www.facebook.com/events/334047523619810/")))
        ->add('adress',TextType::class, array('required'=>1,'label'=>"Adresse"))
        ->add('country',EntityType::class,array('label'=>"Pays",'class'=>'FabienEventsEngineBundle:Country','choice_label'=>'title','required'=>true))
        ->add('city_other',TextType::class,array('label'=>"Autre ville (si vous n'avez pas trouvez votre ville dans la liste)",'required'=>false))
        ->add('type_event',EntityType::class,array("label"=>"Type d'événement",'class'=>'FabienEventsEngineBundle:TypeEvent','choice_label'=>'title',))
        ->add('inscription', ChoiceType::class, array('label'=>'Evénement sur inscription ?',"choices"=>array("non"=>0,"oui"=>1)))
        ->add('day', ChoiceType::class, array('label'=>'jour',"choices"=>array("chaque lundi"=>1,"chaque mardi"=>2,"chaque mercredi"=>3,"chaque jeudi"=>4,"chaque vendredi"=>5,"chaque samedi"=>6,"chaque dimanche"=>7),"required"=>false))
        ->add('dateInscription', DateTimeType::class, array('required'=>0,'label'=>"Date et heure de l'ouverture des inscriptions",'format' => 'dd/MM/yyyy kk:mm'))
        ->add('genderBalance', ChoiceType::class, array('label'=>'Parité guideur & guidé ?',"choices"=>array("non"=>0,"oui"=>1)))
        ->add('file', FileType::class,array("label"=>"Envoyer une image (taille max 1Mo)","required"=>false))
        ->add('Sauvegarder', SubmitType::class)
        ->add('dates', CollectionType::class, array(
              'entry_type'   => DateType::class,
              'allow_add'    => true,
              'allow_delete' => true,
              //ultra important ... sinon la correspondance entre les deux ne marchera pas
              'by_reference' => false,
              "prototype"=> true,
              'data_class' => null,
              "prototype_data"=>new Date()
            ))
          ;

          //Parties qui se modifient selon les droits
          if($options['userRole']=="admin"){
            $builder->add('publish',CheckBoxType::class, array('required'=>false,'label'=>"Publié ?"))
            ->add('valorisation',TextType::class, array('required'=>false,'label'=>"Valorisation"))
            ;
          }




          $formModifier = function (FormInterface $form, Country $country = null) {

              $cities = null === $country ? array() : $country->getCities();


              $form->add('city',EntityType::class,
                array('label'=>'Ville (ou ville la plus proche présente dans la liste)',
                      'class'=>'FabienEventsEngineBundle:City',
                      'choice_label'=>'title',
                      "required"=>true,
                      'choices'=>$cities
                      )
                    );
          };


          $builder->addEventListener(
            FormEvents::PRE_SET_DATA,
            function (FormEvent $eventForm) use ($formModifier) {
                // this would be your entity, i.e. SportMeetup
                $data = $eventForm->getData();

                $formModifier($eventForm->getForm(), $data->getCountry());

                //parties qui se modifient si on édite
                $object= $eventForm->getData();
                $form = $eventForm->getForm();

                /*
                if (!$object || null === $object->getId()) {
                  $form ->add("mail_creator",EmailType::class,array("label"=>"Votre adresse email","required"=>true,"attr"=>array("placeholder"=>"contact@tangoloso.com")))
                    ->add("password_creator",PasswordType::class,array("label"=>"Votre mot de passe","required"=>true))
                    ;
                }
                */

            }
          );


          $builder->get("country")->addEventListener(
           FormEvents::POST_SUBMIT,
           function (FormEvent $event) use ($formModifier) {
                // It's important here to fetch $event->getForm()->getData(), as
                // $event->getData() will get you the client data (that is, the ID)
                $country = $event->getForm()->getData();

                $form=$event->getForm();


                // since we've added the listener to the child, we'll have to pass on
                // the parent to the callback functions!
                $formModifier($form->getParent(), $country);
            }
          );


    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Fabien\EventsEngineBundle\Entity\Event',
            'userRole'=>null
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'fabien_eventsenginebundle_event';
    }


}

src/Fabien/EventsEngineBundle_old/Resources/views/Events/bigeventslisthome.html.twig
{% extends "FabienEventsEngineBundle::layout.html.twig" %}


{% block title %}
{{ "events_list"|trans }}
{% endblock %}


{% block body %}

{% if error_message is defined %}
<div class='container'>
  <div class='alert alert-warning'>
  <h3>{{ "Something_whent_wrong"|trans }}</h3>
  {{ error_message }}
  </div>
</div>
{% endif %}

{% if success_message is defined %}
<div class='container'>
  <div class='alert alert-success'>
  <h3>{{ "Operation_success"|trans }}</h3>
  {{ success_message }}
  </div>
</div>
{% endif %}


<h1>{{ "events_list"|trans }}</h1>

<ul>
  {% for event in listEvents %}

  {% else %}
  <li>{{ "no_event_found"|trans }}</li>
  {% endfor %}
</ul>

<p><a class='button' href="{{ path('events_add') }}">{{ "add_an_event"|trans }}</a></p>

{% endblock %}

src/Fabien/EventsEngineBundle_old/Resources/views/Events/horaires.html.twig
<div class="infosResume">
  <p>

        {{ "a_in"|trans }}
        {% if event.cityOther!="" %}
        {{ event.cityOther}}
        {% else %}
            {% if event.city!="" %}{{ event.city.title}}{% endif %}
        {% endif %}

        {% for date in event.dates %}
          {% if date.start|date('Y-m-d')!=date.end|date('Y-m-d') %}
            {{ "du_form"|trans }} <span itemprop="startDate">{{ date.start|localizeddate('none', 'none', "fr","Europe/Paris","cccc dd LLLL yyyy 'à' HH:mm") }}</span>
            {{ "au_to"|trans }}
            <span itemprop="endDate">{{ date.end|localizeddate('none', 'none', "","Europe/Paris","cccc dd LLLL yyyy 'à' HH:mm") }}</span>
          {% else %}
            <span itemprop="startDate">{{ date.start|localizeddate('none', 'none', "","Europe/Paris","cccc dd LLLL yyyy 'de' HH:mm") }}</span> à {{ date.end|localizeddate('none', 'none', "fr","Europe/Paris","HH:mm") }}
          {% endif %}
        {% endfor %}

  </p>
</div>

src/Fabien/EventsEngineBundle_old/Resources/views/Events/index.html.twig
{% extends "FabienEventsEngineBundle::layout.html.twig" %}


{% block body %}
<h1>Mes évenements ! </h1>

{% endblock %}

src/Fabien/EventsEngineBundle_old/Resources/views/Events/lastEvents.html.twig
{% extends "FabienEventsEngineBundle::layout.html.twig" %}

{% block title %}
{{ events|length }} {{ "events_added_these"|trans }} {{days}} {{ "last_days"|trans }}
{% endblock %}

{% block og %}
{% include 'FabienEventsEngineBundle:General:og.html.twig' with {'titleOG': "Les derniers événements ajoutés","descriptionOG": events|length ~ " événements ajoutés ces "~days~" derniers jours"  ,"imageOG":'/web/img/logo.png'  } only %}
{% endblock %}

{% block body %}

<div class='container'>
  <h1>{{ events|length }} {{ "events_added_these"|trans }} {{days}} {{ "last_days"|trans }} </h1>
</div>

  {% if format=="list" %}
  <div class='container'>
      <ul>
      {% set actualType ="" %}
      {% for event in events %}
        {% if actualType != event.TypeEvent.title %}
          {% set actualType = event.TypeEvent.title %}
          </ul>
            <div class="col-xs-12">
              <h2>{{ actualType }}s</h2>
            </div>
          <ul>
        {% endif %}

          {% for date in event.dates %}
          <li><a href="{{ date.event.urlFb }}">{{ date.event.title}}</a> <br /> le {{ date.start|localizeddate('none', 'none', "","Europe/Paris","cccc dd LLLL") }} -
              {{ date.event.city.title|replace({ (date.event.city.state.country.sortname):"" }) }}, {{date.event.city.state.country.title}}
          </li>
          {% endfor %}
      {% else %}
      <li>{{ "no_event_found"|trans }}</li>
      {% endfor %}
      </ul>
  </div>
  {% else %}


    {% set actualType ="" %}
    {% set bandEvt = "bande-even" %}
    {% for event in events %}
      {% if actualType != event.TypeEvent.title %}
        {% set actualType = event.TypeEvent.title %}

        {% if bandEvt == "bande-odd" %}
          {% set bandEvt = "bande-even" %}
        {% else %}
          {% set bandEvt = "bande-odd" %}
        {% endif %}

        {% if loop.first != true %}
        </div>
        </div>
        {% endif %}

        <div class='{{ bandEvt }}'>
        <div class='container'>
          <div class="col-xs-12">
            <h2>{{ actualType }}s</h2>
          </div>
      {% endif %}

        {% for date in event.dates %}
        {% include 'FabienEventsEngineBundle:Dates:itemDates.html.twig' with {'date': date,"taille":"small"  } only %}
        {% endfor %}
    {% else %}
    <p>{{ "no_event_found"|trans }}</p>



    {% endfor %}

  {% endif %}





</div>



{% endblock %}

{% block codeJs %}

{% endblock %}

src/Fabien/EventsEngineBundle_old/Resources/views/Events/list.html.twig
{% extends "FabienEventsEngineBundle::layout.html.twig" %}


{% block title %}
{{ "events_list"|trans }}
{% endblock %}


{% block body %}

<h1>{{ "events_list"|trans }}</h1>

<ul>
  {% for event in listEvents %}

  {% else %}
  <li>{{ "no_event_found"|trans }}li>
  {% endfor %}
</ul>

<p><a class='button' href="{{ path('events_add') }}">{{ "add_an_event"|trans }}a></p>

{% endblock %}

src/Fabien/EventsEngineBundle_old/Resources/views/Events/listByMonth.html.twig
{% extends "FabienEventsEngineBundle::layout.html.twig" %}


{% block title %}
{{ "events_list"|trans }}
{% endblock %}


{% block body %}

<h1>{{ "events_list"|trans }}</h1>

<ul>
  {% for event in listEvents %}

  {% else %}
  <li>{{ "no_event_found"|trans }}</li>
  {% endfor %}
</ul>

<p><a class='button' href="{{ path('events_add') }}">{{ "add_an_event"|trans }}</a></p>

{% endblock %}

src/Fabien/EventsEngineBundle_old/Resources/views/Events/newFirstPage.html.twig
{% extends "FabienEventsEngineBundle::layout.html.twig" %}

{% block title %}
{{ "add_form"|trans }}
{% endblock %}


{% block body %}

<div class='container'>

{% if error_message is defined %}
  <div class='alert alert-warning'>
  <h3>{{ "something_whent_wrong"|trans }}</h3>
  {{ error_message }}
  </div>
{% endif %}

{% if success_message is defined %}

  <div class='alert alert-success'>
  <h3>{{ "operation_success"|trans }}</h3>
  <p>{{ "validation_needed"|trans }}</p>
  {{ success_message }}
  <img src="{{ asset(
  'img/gif/yes'~random(6)~'.gif'
  )}}" alt="quel succès !">
  </div>
{% endif %}

<div class="col-md-8 col-md-offset-2">
  <h1>{{ "add_an_event_or_lesson"|trans }}</h1>

  <div class="well">
    <p><span class="glyphicon glyphicon-info-sign"></span>{{ "Pour ajouter un événement, un stage ou un cours de tango, vous avez à votre disposition 2 méthodes."|trans }}</p>
  </div>



  <div class="well">
    <h2><span class="glyphicon glyphicon-hand-right"></span> {{ "Méthode 1 : Importer de Facebook"|trans }}</h2>
    <p>
      {{ "Votre événement doit respecter quelques critères"|trans }} :
      <ul>
        <li>{{ "il doit s'agir d'un événement et non d'une page"|trans }}</li>
        <li>{{ "votre événement doit avoir un statut public"|trans }}</li>
        <li>{{ "il doit contenir une photo d'illustration"|trans }}</li>
        <li>{{ "le lieu doit être renseigné"|trans }}</li>
      </ul>
    </p>
    <p><strong>{{ "Saisissez ci-dessous l'adresse de l'événement Facebook à ajouter."|trans }}</strong></p>

    <div class="form-group ">

      <p>
      <input type="text" name="facebookevt" value="" id="fblink" class="form-control" placeholder="https://www.facebook.com/events/333040897051350/">
      </p>

      <p>
      {{"event_type"|trans}}
      <select id='add_fb_type_select' class="selectpicker" title="Choisir un type">
        <option value='#'></option>
        {% for TypeEvt in listTypeEvt %}
          <option value='{{ TypeEvt.id }}'>{{ TypeEvt.title }}</a></option>
        {% endfor %}
      </select>
      </p>

      <p>
      <div id='alert_type'></div>
      <a href="{{ path("events_add") }}/fb" id='addfb' class='btn btn-primary'>{{ "add"|trans }}</a>
      </p>


    </div>
  </div>

  <div class="well">
    <h2><span class="glyphicon glyphicon-hand-right"></span> {{ "Méthode 2 : Utiliser le formulaire d'ajout d'événement"|trans }}</h2>
    <p>{{ "Vous pouvez ajouter un événement directement en utilisant le formulaire prévu à cet effet"|trans }}</p>
    <p><a class='btn btn-primary' href="{{ path("events_add_form")}}">{{ "Formulaire d'ajout"|trans }}</a></p>
  </div>

  <div class="alert alert-warning" role="alert">
    <p><span class="glyphicon glyphicon-alert"></span> {{ "Les événements doivent concerner uniquement le tango argentin. Si ce n'est pas le cas, ils seront supprimés sans préavis."|trans }}</p>
  </div>

</div>



</div>



{% endblock %}

{% block codeJs %}
<script>
$(document).ready(function(){
  $("#addfb").click(function(){
    typeFb=$("#add_fb_type_select").val();
    idFb=$("#fblink").val();
    if(idFb!=""){
      if(typeFb!=""){
        idFb=idFb.replace("https://www.facebook.com/events/","");
        idFb=idFb.replace('/',"");
        cible=$(this).attr("href")+"/"+idFb+"/"+typeFb;
        window.location.href=cible;
      }else{
        $("#alert_type").html("<div class='alert alert-danger' role='alert'>{{"please_choose_type"|trans}} </div>");
      }
    }else{
      $("#alert_type").html("<div class='alert alert-danger' role='alert'>{{"Adresse_fb_manquante"|trans}} </div>");

    }
    return false;
  });
})
</script>
{% endblock %}